from __future__ import annotations

from sqlalchemy import (
    CheckConstraint,
    Column,
    Date,
    Float,
    ForeignKey,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
)

metadata = MetaData()

draws = Table(
    "draws",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("draw_date", Date, nullable=False, unique=True),
    Column("m1", Integer, nullable=False),
    Column("m2", Integer, nullable=False),
    Column("m3", Integer, nullable=False),
    Column("m4", Integer, nullable=False),
    Column("m5", Integer, nullable=False),
    Column("s1", Integer, nullable=False),
    Column("s2", Integer, nullable=False),
    Column("source", Text),
    Column("source_url", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Column("checksum", String(64), nullable=False, unique=True),
    CheckConstraint("m1 between 1 and 50"),
    CheckConstraint("m2 between 1 and 50"),
    CheckConstraint("m3 between 1 and 50"),
    CheckConstraint("m4 between 1 and 50"),
    CheckConstraint("m5 between 1 and 50"),
    CheckConstraint("s1 between 1 and 12"),
    CheckConstraint("s2 between 1 and 12"),
    CheckConstraint("m1 < m2 and m2 < m3 and m3 < m4 and m4 < m5"),
    CheckConstraint("s1 < s2"),
)

main_combinations = Table(
    "main_combinations",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("m1", Integer, nullable=False),
    Column("m2", Integer, nullable=False),
    Column("m3", Integer, nullable=False),
    Column("m4", Integer, nullable=False),
    Column("m5", Integer, nullable=False),
    Column("sum_main", Integer, nullable=False),
    Column("odd_count", Integer, nullable=False),
    Column("even_count", Integer, nullable=False),
    Column("span", Integer, nullable=False),
    Column("gap1", Integer, nullable=False),
    Column("gap2", Integer, nullable=False),
    Column("gap3", Integer, nullable=False),
    Column("gap4", Integer, nullable=False),
    Column("min_gap", Integer, nullable=False),
    Column("max_gap", Integer, nullable=False),
    Column("avg_gap", Float, nullable=False),
    Column("decade_bucket_signature", Text, nullable=False),
    Column("combination_key", Text, nullable=False, unique=True),
)

star_combinations = Table(
    "star_combinations",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("s1", Integer, nullable=False),
    Column("s2", Integer, nullable=False),
    Column("sum_stars", Integer, nullable=False),
    Column("gap", Integer, nullable=False),
    Column("odd_count", Integer, nullable=False),
    Column("even_count", Integer, nullable=False),
    Column("combination_key", Text, nullable=False, unique=True),
)

source_observations = Table(
    "source_observations",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("source", Text, nullable=False),
    Column("source_url", Text),
    Column("observed_at", Text, nullable=False),
    Column("draw_date", Date, nullable=False),
    Column("m1", Integer, nullable=False),
    Column("m2", Integer, nullable=False),
    Column("m3", Integer, nullable=False),
    Column("m4", Integer, nullable=False),
    Column("m5", Integer, nullable=False),
    Column("s1", Integer, nullable=False),
    Column("s2", Integer, nullable=False),
    Column("raw_payload", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("checksum", String(64), nullable=False),
)

feature_snapshots = Table(
    "feature_snapshots",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("as_of_draw_id", Integer, ForeignKey("draws.id"), nullable=False),
    Column("feature_name", Text, nullable=False),
    Column("feature_scope", Text, nullable=False),
    Column("entity_key", Text, nullable=False),
    Column("value", Float, nullable=False),
    Column("created_at", Text, nullable=False),
    UniqueConstraint("as_of_draw_id", "feature_name", "feature_scope", "entity_key"),
)

model_runs = Table(
    "model_runs",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("run_type", Text, nullable=False),
    Column("trained_until_draw_id", Integer, ForeignKey("draws.id")),
    Column("parameters_json", Text, nullable=False),
    Column("metrics_json", Text, nullable=False),
    Column("created_at", Text, nullable=False),
)

backtest_predictions = Table(
    "backtest_predictions",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("model_run_id", Integer, ForeignKey("model_runs.id"), nullable=False),
    Column("predicted_for_draw_id", Integer, ForeignKey("draws.id"), nullable=False),
    Column("rank", Integer, nullable=False),
    Column("m1", Integer, nullable=False),
    Column("m2", Integer, nullable=False),
    Column("m3", Integer, nullable=False),
    Column("m4", Integer, nullable=False),
    Column("m5", Integer, nullable=False),
    Column("s1", Integer, nullable=False),
    Column("s2", Integer, nullable=False),
    Column("score", Float, nullable=False),
    Column("main_hits", Integer, nullable=False),
    Column("star_hits", Integer, nullable=False),
    Column("prize_tier", Text, nullable=False),
)

predictions = Table(
    "predictions",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("model_run_id", Integer, ForeignKey("model_runs.id"), nullable=False),
    Column("generated_at", Text, nullable=False),
    Column("rank", Integer, nullable=False),
    Column("m1", Integer, nullable=False),
    Column("m2", Integer, nullable=False),
    Column("m3", Integer, nullable=False),
    Column("m4", Integer, nullable=False),
    Column("m5", Integer, nullable=False),
    Column("s1", Integer, nullable=False),
    Column("s2", Integer, nullable=False),
    Column("score", Float, nullable=False),
    Column("explanation_json", Text, nullable=False),
)
